/**
 * I LOVE PICKLEBALL - 統合データベース・シーダー (Seeder)
 * 
 * data/ および salvaged_data/ フォルダ内に存在するすべてのJSONデータを読み込み、
 * init.sql で定義したテーブルに対して INSERT 発行を行うためのSQLファイルを自動生成するスクリプトです。
 * 直接DBに接続する代わりに、安全なSQLダンプ（seed_data.sql）を吐き出す構成にしています。
 */

const fs = require('fs');
const path = require('path');

// 読み込み対象のディレクトリ群
const DATA_DIRS = [
    path.join(__dirname, '../data'),
    path.join(__dirname, '../salvaged_data')
];

// 出力先のSQLファイル
const OUTPUT_FILE = path.join(__dirname, 'seed_data.sql');

/**
 * ファイル名や配置フォルダから、INSERT先のテーブル名を推論するマッパー
 */
const getTableName = (basename, dirPath) => {
    // プレフィックスの除去
    let name = basename.replace('dummy_', '').replace('master_', '');

    // 特定の命名規則のマッピング
    if (name === 'tournaments_comprehensive' || name === 'local_events') return 'events';
    if (name.includes('drills')) return 'drills';
    if (name === 'kanto' || name === 'chugoku_shikoku') return 'facilities';
    if (name === 'articles_seed') return 'articles';
    if (name === 'senior_pros' || name === 'domestic_players') return 'pro_players';
    if (name === 'apparel_and_bags') return 'gears_apparel';
    if (name === 'niche_gears') return 'gears_accessories';

    // サルベージから発掘された脱落スキーママッピング
    if (name === 'top_coaches') return 'coaches';
    if (name === 'certifications') return 'coach_certifications';
    if (name === 'injury_prevention') return 'injury_preventions';

    // gearsフォルダ以下は gears_xxx にマッピング
    if (dirPath.includes('gear') && !name.startsWith('gears_')) {
        return `gears_${name}`;
    }

    return name;
};

/**
 * SQLの文法に合わせて値をエスケープ・クォートする
 */
const escapeSqlValue = (val) => {
    if (val === null || val === undefined) return 'NULL';
    if (typeof val === 'number') return val;
    if (typeof val === 'boolean') return val ? 'TRUE' : 'FALSE';

    // 文字列内のシングルクォートをエスケープ
    const escapedStr = String(val).replace(/'/g, "''");
    return `'${escapedStr}'`;
};

const main = () => {
    let sqlOutput = '-- ==========================================\n';
    sqlOutput += '-- I LOVE PICKLEBALL 自動生成シードデータ\n';
    sqlOutput += '-- Generated by seeder.js\n';
    sqlOutput += '-- ==========================================\n\n';

    let totalRows = 0;
    let totalFiles = 0;

    const parseDirectory = (dir) => {
        if (!fs.existsSync(dir)) return;

        const items = fs.readdirSync(dir);
        items.forEach(item => {
            const fullPath = path.join(dir, item);
            if (fs.statSync(fullPath).isDirectory()) {
                parseDirectory(fullPath); // ディレクトリは再起的に探索
            } else if (item.endsWith('.json')) {
                const basename = path.basename(item, '.json');
                const tableName = getTableName(basename, dir);

                try {
                    const rawData = fs.readFileSync(fullPath, 'utf8');
                    let jsonData = JSON.parse(rawData);

                    // advanced_shots.json など、ルートがObjectで items に配列が入っているケースへの対応
                    if (!Array.isArray(jsonData) && jsonData.items && Array.isArray(jsonData.items)) {
                        jsonData = jsonData.items;
                    }

                    // JSONが配列形式（複数レコード）の場合のみ処理
                    if (Array.isArray(jsonData) && jsonData.length > 0) {
                        sqlOutput += `-- Seeding [${tableName}] from: ${item}\n`;

                        jsonData.forEach(row => {
                            const columns = Object.keys(row);
                            // 配列などの中身はJSON文字列化してからSQL用にエスケープする
                            const values = Object.values(row).map(val => {
                                if (Array.isArray(val) || typeof val === 'object' && val !== null) {
                                    return escapeSqlValue(JSON.stringify(val));
                                }
                                return escapeSqlValue(val);
                            });
                            sqlOutput += `INSERT INTO ${tableName} (${columns.join(', ')}) VALUES (${values.join(', ')});\n`;
                            totalRows++;
                        });
                        sqlOutput += '\n';
                        totalFiles++;
                    }
                } catch (e) {
                    console.error(`[Skip] 読み込みエラー (${item}): ${e.message}`);
                }
            }
        });
    };

    console.log('JSONデータのパースを開始します...');
    DATA_DIRS.forEach(parseDirectory);

    // SQLファイルとして出力
    fs.writeFileSync(OUTPUT_FILE, sqlOutput, 'utf8');

    console.log('✅ シードSQLの生成が完了しました！');
    console.log(`- 参照したJSONファイル数 : ${totalFiles} ファイル`);
    console.log(`- 生成されたINSERT文の数 : ${totalRows} レコード`);
    console.log(`- 出力先パス : ${OUTPUT_FILE}`);
};

main();
